---
- hosts:
  - mdms
  - tbs
  - sdss
  - sdcs
  - lias
  
  tags:
    - always
  
  pre_tasks:
    - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] }}"
      run_once: true

- hosts: all
  name: "Set facts"
  gather_facts: no 
  roles: 
    - powerflex-facts
  tags: powerflex-facts

- hosts: mdms
  name: "Install PowerFlex MDM"
  gather_facts: no
  become: true
  roles:
   - { role: "powerflex-mdm", when: "'EMC-ScaleIO-mdm' not in ansible_facts.packages" }
  tags: powerflex-mdm

- hosts: tbs
  name: "Install PowerFlex TB"
  gather_facts: no
  become: true
  roles:
   - { role: "powerflex-tb", when: "'EMC-ScaleIO-mdm' not in ansible_facts.packages" }
  tags: powerflex-tb

- hosts: mdms
  name: "Configure PowerFlex storage"
  gather_facts: no
  roles:
    - { role: "powerflex-config", when: "'EMC-ScaleIO-mdm' not in ansible_facts.packages" }
  tags: powerflex-config

- hosts: sdss
  name: "Install PowerFlex SDS"
  gather_facts: no
  become: true
  roles:
    - { role: "powerflex-sds", when: "'EMC-ScaleIO-sds' not in ansible_facts.packages" }
  tags: powerflex-sds

- hosts: all
  name: "Install PowerFlex LIA"
  gather_facts: no
  become: true
  roles:
    - { role: "powerflex-lia", when: "'EMC-ScaleIO-lia' not in ansible_facts.packages" }
  tags: powerflex-lia

- hosts: sdcs
  name: "Install PowerFlex SDC"
  gather_facts: no
  become: true
  roles:
    - { role: "powerflex-sdc", when: "'EMC-ScaleIO-sdc' not in ansible_facts.packages" }
  tags: powerflex-sdc

