- name: include vars
  include_vars: ../vars/main.yaml

- include: ../../powerflex-common/tasks/install_powerflex.yaml

- name: login to MDM
  command: scli --login --username admin --password "{{ password }}" --approve_certificate
  run_once: true
  delegate_to: "{{ powerflex_config_ip }}"

- name: Add multiple SDC
  command: >
    scli --add_sdc 
    --sdc_ip {{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }}  
    --sdc_name "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
  delegate_to: "{{ powerflex_config_ip }}"

- name: Configure MDM IPs in drv_cfg
  replace:
   path: /etc/emc/scaleio/drv_cfg.txt 
   regexp: '^#mdm(.*)'
   replace: 'mdm {{ cluster_vip }}'

- name: Restart scini service
  service:
    name: scini
    state: restarted
